### PR TITLE
Fixed overflowing calculations

### PR DESCRIPTION
**Pull request by ify47**
i made the font bigger, and it reduces when the number becomes larger and increases when you delete them, i had to add another div to result, had no choice, please review code and test app. 

regards🙏

### CODE REVIEW

**Comment by N3v1** [comment]
Hi @ify47, I'm sorry but i can't merge your PR because your branch has conflicts with mine

**Comment by N3v1** [comment]
Bildschirmfoto 2023-08-24 um 16 28 13
Bildschirmfoto 2023-08-24 um 16 28 31

**Comment by ify47** [comment]
hello friend, just fixed conflicts

regards

**Comment by N3v1** [comment]
Thank you for your work @ify47

**Pull request merged**
