### PR TITLE
Enhancement: Display Previous Expression Above Result - issue #8

### PR DESCRIPTION
**Pull request by DoonOnthon**
Hey there,

I've tackled the hiccup in my previous code. Big thanks for pointing it out! I've synced my fork and everything should be good to go now.

Added Feature: You can now see the previous expression after the calculation.

Fixed Issue: 🌟Feature: See calculation that made up result 🌟Feature: See calculation that made up result [#8]
Your thoughts and input is appreciated, so please keep 'em coming!

later,
DoonOnthon

### CODE REVIEW

**Comment by DoonOnthon** [comment]
Made a mistake with the comments you wrote in index.js, thats why i closed it give me a minute and ill create a new request with the comments back in there.

**Comment by N3v1** [comment]
OK. I'm a little confused right now @DoonOnthon . What I understood: You made a mistake and closed the PR and want to make changes and publish them via a new PR?! If so, I'll close this PR

**Comment by DoonOnthon** [comment]
Thank you for your prompt response. I apologize for any confusion I may have caused. Upon further reflection, I realized that I mistakenly overlooked the option to push the commits through the existing pull request. Please accept my apologies for this oversight.

The changes have now been correctly pushed and integrated into the original pull request. I'm pleased to confirm that it is now ready for your review, appreciate your patience.

**Comment by N3v1** [comment]
All good, so the changes are in this PR now? @DoonOnthon

**Comment by DoonOnthon** [comment]
Indeed

**Comment by N3v1** [comment]
Okay, @DoonOnthon 🙏
Have a little patience. I thank you for your patience and your help.

Hey @jiri132 👋,
I could use some help checking this PR. I don't know if his changes could break the % bug fix you did.

**Comment by N3v1** [comment]
You would only need to check the index.js file. Only if you have the time and inclination

**Comment by DoonOnthon** [comment]
Sorry for the vague messages earlier – my internet was acting up. Everything's resolved now, and I'm ready to merge from THIS pull request:

Thanks for your patience, once again!

**Comment by N3v1** [comment]
All good, I just brought in a second person to review your edits. It might take a while

**Review by N3v1 — CHANGES_REQUESTED** [review]
Hi @DoonOnthon,
Thanks for your help, I have a few more ideas: I find that the upper div container, where the calculations are shown, is way too close to the result. Maybe a bit of padding or spacing?

**Comment by N3v1** [comment]
@DoonOnthon, I won't see your changes until Friday, until then I can't be reached. Just so you don't wonder why I won't answer

Best regards 
NH

**Comment by jiri132** [comment]
Hey @N3v1 , 

Is it still necessary for me to look at the file to see if it maybe would break the new % usage I wrote?

Kind Regards,
JB

**Comment by jiri132** [comment]
I Have reviewed the index.js file and it doesn't look like it broke anything

**Comment by N3v1** [comment]
Hi @jiri132, thanks but I already did it

Thank you kindly 🙏
Beat regards
NH

**Pull request merged**
